version: '2'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  minio:
    container_name: Minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: mlflow_api
    ports:
      - "5001:5000"   # Exponemos el puerto 5000 del contenedor en el 5001 del host
    depends_on:
      - mysql
      - minio

  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile.jupyterlab
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  mysql_data:
