FROM jupyter/datascience-notebook:latest

USER root
RUN pip install --no-cache-dir mlflow pymysql sqlalchemy

USER ${NB_UID}
WORKDIR /home/jovyan/work

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
