FROM python:3.8-slim

WORKDIR /app

# Copia el archivo de requerimientos e instala dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la API
COPY api.py .

EXPOSE 5000
CMD ["python", "api.py"]
